### ISSUE TITLE
imageData.ts のIDをDBのIDと一致するように変更

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#130]
# Done の定義
imageData.ts のIDがDBのIDと一致するように変更されていること

# 補足情報

https://github.com/nekochans/lgtm-cat/issues/16 の対応でLGTM画像のデータをDBに登録した。
DBのIDは1からスタートしているがimageData.ts は0からスタートしており、IDがずれているのでDB側に合わせる形で修正する。

**Comment by kobayashi-m42** [comment]
@keitakn データの修正だから1ポイントで良いかな？

**Comment by keitakn** [comment]
@kobayashi-m42 issue作成ありがとう！
1ポイントで問題なさそう👌
