### ISSUE TITLE
猫画像アップロード確認でプレビュー画像が表示されないことがある

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#152]
# 概要

猫画像アップロード確認でプレビュー画像が表示されないことがある

# 再現手順

1. 「猫ちゃん画像をアップロード」ページを表示
2.  画像を選択しプレビューを表示
3.  モーダルを閉じる (アップロードをする/しないに関わらず発生)
5. 先ほどと同じ画像を選択 
6. プレビュー画面が表示されない

手順 4. で 2. とは異なる画像を選択した場合は、プレビューが表示される

# 再現環境

MacOS Chrome最新版で発生。

他のOS、ブラウザでも同様の問題が発生する可能性がある。

# このバグによって引き起こされる問題

プレビュー画面が表示されないことがあり、ユーザーが猫画像をアップロードできない可能性がある。
ただし、このような操作をすることは稀だと思うので優先度は低くても問題なさそう。

**Comment by keitakn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/lgtm-cat-602a31ca1eebd0000ff95261/issues/nekochans/lgtm-cat-frontend/152?planning-poker) with ZenHub @kobayashi-m42

**Comment by keitakn** [comment]
再度同じ画像をアップロードしたタイミングでイベントが取れないのがツライ。

かといってモーダルを閉じたタイミングでアップロード済のファイルをStateから削除などをしても上手く動作しない。

根本的に対応方法を見直す必要がある。

時間がかかりそうなので一旦他の課題を解決する。

**Comment by keitakn** [comment]
新デザインで解決したので、新しいデザインがリリースされたらCloseする。

**Comment by keitakn** [comment]
新デザインがリリースされたので本件は解決、よってクローズする。
