### ISSUE TITLE
CIの設定を追加

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#17]
# Doneの定義
- PRに対してテスト + Lintが実行される状態になっている事
- テスト + Lintが失敗している場合はPRがマージ出来ない状態になっている事

 # 補足情報
本来リリース後でも問題はない課題だが、今ドメインの名前解決の問題があるので、その待ち時間の間にこれをやっておく。
早めに対応する事でデグレ等のリスクを減らせるので早めに対応する意味はそれなりにあるハズ。

**Comment by keitakn** [comment]
@kobayashi-m42 
ドメインの名前解決出来ない問題が待ち時間あって、進められないからこれ先にやった🐱！

https://github.com/nekochans/lgtm-cat-frontend/pull/18 で既に対応しちゃってるから事後だけどストーリーポイント3とか大丈夫かな？？

**Comment by kobayashi-m42** [comment]
@keitakn 課題の追加ありがとう！後で追加しようと思って忘れてた💦
3ポイントでいいと思う！
