### ISSUE TITLE
利用規約のサイト利用自体に適用する内容に変更する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#185]
# Done の定義
下記の文章を
```
登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
```
下記に変更する
```
ご利用の皆さま（以下，「ユーザー」といいます。）は、本サービスをご利用頂くにあたり、本規約の全ての条項について同意頂く必要があります。本サービスをご利用頂いた場合、本規約の内容を理解し、かつ、本規約の全ての条項について同意したものとみなします。
```

# 補足情報
LGTMeow は、登録が不要なサービスのため利用規約をサイト利用自体に適用するため

**Comment by keitakn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/lgtm-cat-602a31ca1eebd0000ff95261/issues/nekochans/lgtm-cat-frontend/185?planning-poker) with ZenHub @kobayashi-m42
