### ISSUE TITLE
問い合わせフォームに同意確認項目を追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#186]
# Done の定義
プライバシーポリシーの問い合わせフォームに、下記にような同意確認項目が追加されていること

```
・プライバシーポリシーに同意して送信する
※問い合わせ内容およびご入力頂いた個人情報はお問い合わせへの回答を目的としてのみ使用し、プライバシーポリシーに則り適切に取り扱うものとします。 プライバシーポリシー(URLURLURL)をお読みいただき、同意の上、お問い合わせを送信してください。
```

**Comment by keitakn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/lgtm-cat-602a31ca1eebd0000ff95261/issues/nekochans/lgtm-cat-frontend/186?planning-poker) with ZenHub @kobayashi-m42

**Comment by keitakn** [comment]
問い合わせフォームに「プライバシーポリシーに同意して送信する」のチェックボックスを追加。

![Form](https://user-images.githubusercontent.com/11032365/179014940-80ccd45a-9cb4-4866-ad40-4330f998048b.png)
