### ISSUE TITLE
OGP用の画像とmetaタグの設定を行う

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#20]
# Doneの定義
- OGP画像が設定されている事
- タイトルタグ等の最低限必要なメタタグが設定されている事

 # 補足情報
サービスの性質上、以下のような動的なOGP画像生成は必要ないので、固定でOK。

https://ji23-dev.com/blogs/nextjs-ogp

OGP画像はあまりデザインに凝りすぎると時間がかかるので、ある程度で妥協する。

**Comment by keitakn** [comment]
@kobayashi-m42 これも事後で対応してしまった後なんだけど、ストーリーポイント5とかかな🐱？（画像作るのが結構大変だった・・・）

https://github.com/nekochans/lgtm-cat-frontend/pull/25

**Comment by kobayashi-m42** [comment]
@keitakn 5ポイントでいいと思う！
