### ISSUE TITLE
サイトマップを作成するエンドポイントを実装する

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#21]
# Doneの定義
- XML形式のサイトマップを返すエンドポイントが実装されている事
- Google Search ConsoleにサイトマップのURLが登録されている事

 # 補足情報
以下の情報が参考になる。
https://zenn.dev/catnose99/articles/c441954a987c24

**Comment by keitakn** [comment]
@kobayashi-m42 既に対応済なんだけど、XMLサイトマップは送信しておいたほうが良さそうだなと思ったから追加したよ👍
ストーリーポイント3くらいだったと思う🐱！

https://github.com/nekochans/lgtm-cat-frontend/pull/23

**Comment by kobayashi-m42** [comment]
@keitakn 3ポイントでいいと思う！🐱
