### ISSUE TITLE
ランダムボタンの実装

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#28]
# Doneの定義
- ランダムに画像が更新されること

 # 補足情報
[optional]

**Comment by keitakn** [comment]
# めも
React Contextを使う、Reduxなどは現在状況が安定していないので、様子見。

**Comment by keitakn** [comment]
参考になりそうな分かりやすい記事を見つけたので追加🐱

https://panda-program.com/posts/react-usecontext-usereducer#usecontext%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9
