### ISSUE TITLE
画像要素はNext.jsのImageコンポーネントを利用するように変更を行う

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#33]
# Doneの定義
- 画像がプリロードされるように変更されている事（Next.jsのImageコンポーネントを使えば自動的にそうなる）

 # 補足情報

PageSpeed Insightsの指摘内容。

画像のプリロードを行う事でパフォーマンスが大幅に改善される可能性がある。

![preload](https://user-images.githubusercontent.com/11032365/111418897-d9104e00-872b-11eb-8ec4-9bbaa7a83328.png)

**Comment by keitakn** [comment]
Next.jsのImageComponentについての参考URL。

https://qiita.com/ttexan/items/0680b09cb9fc071e79a0

https://nextjs.org/docs/api-reference/next/image

**Comment by keitakn** [comment]
めも

Doneの定義にある、下記の部分はバックエンド側のAPIから画像のwidth と heightが返ってこないと実施が難しいので、この課題のDoneの定義からは外し別の課題に分離する。

>img ソースに width と height が明示的に指定されるようになっている事

**Comment by kobayashi-m42** [comment]
@keitakn ポイントをつけてなかったけれど、3か5くらいかな？スタイルの修正とモックの作成に思ったより時間かかってしまった🐱

**Comment by keitakn** [comment]
@kobayashi-m42 対応ありがとう🐱モックの件があるから5で良いかも！
