### ISSUE TITLE
LGTM画像のデータを正式に作成した画像に変更する

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#34]
# Doneの定義
- [src/utils/imageData.ts](https://github.com/nekochans/lgtm-cat-frontend/blob/main/src/utils/imageData.ts) 内のLGTM画像URLが https://github.com/nekochans/lgtm-cat-backend/pull/4 で作成したWebP形式の正式な物に変更されている事

**Comment by keitakn** [comment]
@kobayashi-m42 課題なかったから、作っておいた🐱！

画像作って、URLを配列にコピーしてって作業内容だから単純だけど画像の枚数が多いと作業量は増えそう、最初は50枚〜100枚くらいの画像を作ると仮定すると、ストーリーポイント2くらいかな？？

**Comment by kobayashi-m42** [comment]
@keitakn 追加ありがとう！2ポイントで！

> 最初は50枚〜100枚くらい
そうだね、これくらいあれば大丈夫な気がする🐱
