### ISSUE TITLE
htmlタグのprefix属性にOGP画像の利用を宣言する内容を追加する

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#36]
# Doneの定義
- HTMLのprefixに以下が追加されている事

```
<html prefix="og: https://ogp.me/ns#">
```

 # 補足情報
https://mirai-creators.com/2199/
https://panda-program.com/posts/nextjs-html-prefix

既にOGP画像の設定は完了しているがprefix属性を付けるのが正式な手順なようなので対応しておく。

**Comment by keitakn** [comment]
@kobayashi-m42 SlackのOGPが表示されなかったりする件があるから一応、追加してみた🐱

解決しない可能性もあるけど、一応、prefixあるのが正式な手順みないだし、一応って感じ、ストーリーポイントは2とかで大丈夫だと思うけど、どうかな？？

https://ogp.me/

**Comment by kobayashi-m42** [comment]
@keitakn うん！2ポイントでいいと思う！
