### ISSUE TITLE
/api 配下のURLに通信する際は相対パスでの指定を行う形に変更する

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#58]
# Doneの定義
- 表題の件が実施されている事

https://github.com/nekochans/lgtm-cat-frontend/blob/21c80cf18e6657aaeab8c03ee29399ae7af94dda/src/infrastructure/repository/ImageRepository.ts#L8

この部分を `const url = '/api/lgtm/images';` のように変更しさらに `/api` 以下の部分も定数化すると良さそう。

 # 補足情報
現状はVercelのPreviewの環境変数を書き換えないとエラーになってしまう。

相対パスで指定するように変更する事で環境変数の書き換えなしで動作確認が可能になるので、そのように対応する。

**Comment by kobayashi-m42** [comment]
@keitakn 1ポイントくらいかな？🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！1ポイントで問題ないと思う🐱
