### ISSUE TITLE
利用規約・プライバシーポリシーページに余白を追加する(スマホで表示のみ)

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#63]
# Doneの定義
- スマホで表示した際に、利用規約・プライバシーポリシーページに余白が追加されていること

 # 補足情報
現状だと画面いっぱいにテキストが表示されているので、余白を追加する。
スマホでの利用規約・プライバシーポリシーページはほぼないので優先度は低いが、すぐに直せるので時間ができたタイミングで対応する。

**Comment by kobayashi-m42** [comment]
@keitakn スタイルを修正するだけだから1ポイントかな？

**Comment by keitakn** [comment]
@kobayashi-m42 うん！1ポイントで大丈夫そう🐱！
