### ISSUE TITLE
モバイルでLGTM画像を選択した際のスタイルを選択前の状態に戻す

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#66]
# Doneの定義
- モバイルでLGTM画像をしたした際のスタイルが選択前の状態に戻っていること

 # 補足情報
モバイルでLGTM画像を選択(タップ)した際に画像が薄く表示されるが、タップ後も薄く表示され続けてしまっているので修正する。

**Comment by kobayashi-m42** [comment]
@keitakn Opacity変更するだけだから、1ポイントかな？

**Comment by keitakn** [comment]
@kobayashi-m42 うん！1ポイントで大丈夫そう🐱
