### ISSUE TITLE
リモートアドレス、ユーザーエージェントについてプライバシーポリシーに追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-frontend#72]
# Doneの定義
- 表題の件が実装されていること

 # 補足情報
画像アップロード機能リリース時には追加する必要がある

**Comment by kobayashi-m42** [comment]
忘れそうだったので、先に課題として追加しておく。

**Comment by keitakn** [comment]
リリース優先の為、一旦リモートアドレス等は保存しないようになったので、こちらはクローズ。
